name: Laravel

on:
  push:
    branches: 
      - test
      - master
  pull_request:
    branches: 
      - test
      - master 

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit

    - name: Configure Application
      run: |
        cp .env.example .env
        php artisan key:generate
    - name: Migrate Database
      run:
        php artisan migrate
    
    - name: Configure Laravel Dusk
      run: |
        php artisan dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`
        chmod -R 0755 vendor/laravel/dusk/bin/
        
    - name: Execute Dusk tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: laravel
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USER: root
        APP_URL: "http://127.0.0.1:8000"
      run: |
        php artisan serve  > /dev/null 2>&1 &
        php artisan dusk 
    - name: Upload Screenshots
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: tests/Browser/screenshots